export const FAKE_CONTACTS = [
    {
        id: 0,
        name: 'amy',
        date_met: '2020-06',
        location: 'New York, NY',
        email: 'something@something.com',
        notes: 'MLH Fellow',
        image: 'https://api.adorable.io/avatars/150/test.png',
    },
    {
        id: 1,
        name: 'amy',
        date_met: '2020-06',
        location: 'New York, NY',
        email: 'something@something.com',
        notes: 'MLH Fellow',
        image: 'https://api.adorable.io/avatars/150/test.png',
    },
    {
        id: 2,
        name: 'amy',
        date_met: '2020-06',
        location: 'New York, NY',
        email: 'something@something.com',
        notes: 'MLH Fellow',
        image: 'https://api.adorable.io/avatars/150/test.png',
    },
    {
        id: 3,
        name: 'amy',
        date_met: '2020-06',
        location: 'New York, NY',
        email: 'something@something.com',
        notes: 'MLH Fellow',
        image: 'https://api.adorable.io/avatars/150/test.png',
    },
    {
        id: 4,
        name: 'amy',
        date_met: '2020-06',
        location: 'New York, NY',
        email: 'something@something.com',
        notes: 'MLH Fellow',
        image: 'https://api.adorable.io/avatars/150/test.png',
    },
];

export const FAKE_GROUPS = [
    {
        id: 0,
        region: 'Global',
        name: 'MLH Fellows',
        type: 'Friends',
        contacts: FAKE_CONTACTS,
        description: 'Friendly people!!!',
    },
    {
        id: 1,
        region: 'Americas',
        name: 'The Lei\'s',
        type: 'Family',
        contacts: [],
        description: 'Friendly people!!!',
    },
];
